# EDA

In [149]:
import numpy as np 

### Load Data Using Numpy genfromtxt

In [179]:
data = np.genfromtxt('Mall_Customers.csv', dtype=['i8','U6','i8','i8','i8'], names=['id', 'Gender', 'Age', 'AnnualIncome','Spending'], delimiter=',', skip_header=1)
data

array([(  1, 'Male', 19,  15, 39), (  2, 'Male', 21,  15, 81),
       (  3, 'Female', 20,  16,  6), (  4, 'Female', 23,  16, 77),
       (  5, 'Female', 31,  17, 40), (  6, 'Female', 22,  17, 76),
       (  7, 'Female', 35,  18,  6), (  8, 'Female', 23,  18, 94),
       (  9, 'Male', 64,  19,  3), ( 10, 'Female', 30,  19, 72),
       ( 11, 'Male', 67,  19, 14), ( 12, 'Female', 35,  19, 99),
       ( 13, 'Female', 58,  20, 15), ( 14, 'Female', 24,  20, 77),
       ( 15, 'Male', 37,  20, 13), ( 16, 'Male', 22,  20, 79),
       ( 17, 'Female', 35,  21, 35), ( 18, 'Male', 20,  21, 66),
       ( 19, 'Male', 52,  23, 29), ( 20, 'Female', 35,  23, 98),
       ( 21, 'Male', 35,  24, 35), ( 22, 'Male', 25,  24, 73),
       ( 23, 'Female', 46,  25,  5), ( 24, 'Male', 31,  25, 73),
       ( 25, 'Female', 54,  28, 14), ( 26, 'Male', 29,  28, 82),
       ( 27, 'Female', 45,  28, 32), ( 28, 'Male', 35,  28, 61),
       ( 29, 'Female', 40,  29, 31), ( 30, 'Female', 23,  29, 87),
       ( 31, 'Male', 

**Note:**

- **Use U6 instead of S6**

**Reference**
- https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html
- https://stackoverflow.com/questions/33655641/b-character-added-when-using-numpy-loadtxt

In [180]:
#Check data type of array
type(data)

numpy.ndarray

In [181]:
# Check data type of individual columns
data.dtype

dtype([('id', '<i8'), ('Gender', '<U6'), ('Age', '<i8'), ('AnnualIncome', '<i8'), ('Spending', '<i8')])

In [182]:
# Check shape of array
data.shape

(200,)

In [183]:
# Check dimension of array
data.ndim

1

In [184]:
# Extract first record
first_record = data[0]
first_record

(1, 'Male', 19, 15, 39)

In [185]:
# Check data type of first record
type(first_record)

numpy.void

It looks like tuple but it actually is numpy.void data type.

- https://stackoverflow.com/questions/25247190/how-to-use-numpy-void-type

In [186]:
# Filter gender with male
# Will use the list to double check when doing conversion
data['Gender'] == 'Male'

array([ True,  True, False, False, False, False, False, False,  True,
       False,  True, False, False, False,  True,  True, False,  True,
        True, False,  True,  True, False,  True, False,  True, False,
        True, False, False,  True, False,  True,  True, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False,  True, False,  True, False,  True,  True,  True, False,
       False,  True,  True, False, False,  True, False,  True, False,
       False, False,  True,  True, False,  True, False, False,  True,
        True,  True, False, False,  True, False, False, False, False,
       False,  True,  True, False, False,  True, False, False,  True,
        True, False, False,  True,  True,  True, False, False,  True,
        True,  True,  True, False, False,  True, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
        True,  True,

**We will be converting Male to 1 and Female to 0.**

In [187]:
# Try np.where without actual assignment. Check if conversion is ok.
np.where(data['Gender'] == 'Male', 1, 0)

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1])

In [188]:
# Perform actual conversion
data['Gender'] = np.where(data['Gender'] == 'Male', 1, 0)
data

array([(  1, '1', 19,  15, 39), (  2, '1', 21,  15, 81),
       (  3, '0', 20,  16,  6), (  4, '0', 23,  16, 77),
       (  5, '0', 31,  17, 40), (  6, '0', 22,  17, 76),
       (  7, '0', 35,  18,  6), (  8, '0', 23,  18, 94),
       (  9, '1', 64,  19,  3), ( 10, '0', 30,  19, 72),
       ( 11, '1', 67,  19, 14), ( 12, '0', 35,  19, 99),
       ( 13, '0', 58,  20, 15), ( 14, '0', 24,  20, 77),
       ( 15, '1', 37,  20, 13), ( 16, '1', 22,  20, 79),
       ( 17, '0', 35,  21, 35), ( 18, '1', 20,  21, 66),
       ( 19, '1', 52,  23, 29), ( 20, '0', 35,  23, 98),
       ( 21, '1', 35,  24, 35), ( 22, '1', 25,  24, 73),
       ( 23, '0', 46,  25,  5), ( 24, '1', 31,  25, 73),
       ( 25, '0', 54,  28, 14), ( 26, '1', 29,  28, 82),
       ( 27, '0', 45,  28, 32), ( 28, '1', 35,  28, 61),
       ( 29, '0', 40,  29, 31), ( 30, '0', 23,  29, 87),
       ( 31, '1', 60,  30,  4), ( 32, '0', 21,  30, 73),
       ( 33, '1', 53,  33,  4), ( 34, '1', 18,  33, 92),
       ( 35, '0', 49,  33, 14),

The gender columns still remain as string.

Convert array with dtype void to numpy array.

https://stackoverflow.com/questions/53067064/convert-numpy-void-to-numpy-ndarray

In [189]:
data_list = data.tolist()
data_list

[(1, '1', 19, 15, 39),
 (2, '1', 21, 15, 81),
 (3, '0', 20, 16, 6),
 (4, '0', 23, 16, 77),
 (5, '0', 31, 17, 40),
 (6, '0', 22, 17, 76),
 (7, '0', 35, 18, 6),
 (8, '0', 23, 18, 94),
 (9, '1', 64, 19, 3),
 (10, '0', 30, 19, 72),
 (11, '1', 67, 19, 14),
 (12, '0', 35, 19, 99),
 (13, '0', 58, 20, 15),
 (14, '0', 24, 20, 77),
 (15, '1', 37, 20, 13),
 (16, '1', 22, 20, 79),
 (17, '0', 35, 21, 35),
 (18, '1', 20, 21, 66),
 (19, '1', 52, 23, 29),
 (20, '0', 35, 23, 98),
 (21, '1', 35, 24, 35),
 (22, '1', 25, 24, 73),
 (23, '0', 46, 25, 5),
 (24, '1', 31, 25, 73),
 (25, '0', 54, 28, 14),
 (26, '1', 29, 28, 82),
 (27, '0', 45, 28, 32),
 (28, '1', 35, 28, 61),
 (29, '0', 40, 29, 31),
 (30, '0', 23, 29, 87),
 (31, '1', 60, 30, 4),
 (32, '0', 21, 30, 73),
 (33, '1', 53, 33, 4),
 (34, '1', 18, 33, 92),
 (35, '0', 49, 33, 14),
 (36, '0', 21, 33, 81),
 (37, '0', 42, 34, 17),
 (38, '0', 30, 34, 73),
 (39, '0', 36, 37, 26),
 (40, '0', 20, 37, 75),
 (41, '0', 65, 38, 35),
 (42, '1', 24, 38, 92),
 (43, '

In [190]:
type(data_list)

list

In [191]:
data_new = np.array(data_list)
data_new

array([['1', '1', '19', '15', '39'],
       ['2', '1', '21', '15', '81'],
       ['3', '0', '20', '16', '6'],
       ['4', '0', '23', '16', '77'],
       ['5', '0', '31', '17', '40'],
       ['6', '0', '22', '17', '76'],
       ['7', '0', '35', '18', '6'],
       ['8', '0', '23', '18', '94'],
       ['9', '1', '64', '19', '3'],
       ['10', '0', '30', '19', '72'],
       ['11', '1', '67', '19', '14'],
       ['12', '0', '35', '19', '99'],
       ['13', '0', '58', '20', '15'],
       ['14', '0', '24', '20', '77'],
       ['15', '1', '37', '20', '13'],
       ['16', '1', '22', '20', '79'],
       ['17', '0', '35', '21', '35'],
       ['18', '1', '20', '21', '66'],
       ['19', '1', '52', '23', '29'],
       ['20', '0', '35', '23', '98'],
       ['21', '1', '35', '24', '35'],
       ['22', '1', '25', '24', '73'],
       ['23', '0', '46', '25', '5'],
       ['24', '1', '31', '25', '73'],
       ['25', '0', '54', '28', '14'],
       ['26', '1', '29', '28', '82'],
       ['27', '0', '45', 

All dtype is string. Will convert all to int.

In [199]:
data_new = data_new.astype(int)
data_new

array([[  1,   1,  19,  15,  39],
       [  2,   1,  21,  15,  81],
       [  3,   0,  20,  16,   6],
       [  4,   0,  23,  16,  77],
       [  5,   0,  31,  17,  40],
       [  6,   0,  22,  17,  76],
       [  7,   0,  35,  18,   6],
       [  8,   0,  23,  18,  94],
       [  9,   1,  64,  19,   3],
       [ 10,   0,  30,  19,  72],
       [ 11,   1,  67,  19,  14],
       [ 12,   0,  35,  19,  99],
       [ 13,   0,  58,  20,  15],
       [ 14,   0,  24,  20,  77],
       [ 15,   1,  37,  20,  13],
       [ 16,   1,  22,  20,  79],
       [ 17,   0,  35,  21,  35],
       [ 18,   1,  20,  21,  66],
       [ 19,   1,  52,  23,  29],
       [ 20,   0,  35,  23,  98],
       [ 21,   1,  35,  24,  35],
       [ 22,   1,  25,  24,  73],
       [ 23,   0,  46,  25,   5],
       [ 24,   1,  31,  25,  73],
       [ 25,   0,  54,  28,  14],
       [ 26,   1,  29,  28,  82],
       [ 27,   0,  45,  28,  32],
       [ 28,   1,  35,  28,  61],
       [ 29,   0,  40,  29,  31],
       [ 30,  

In [200]:
data_new.shape

(200, 5)

In [201]:
data_new.ndim

2